name: 'Git Autotag'
description: 'Tag the repository when the action runs'
inputs:
  tag:
    description: The tag to create
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "Attempting to create a lightweight tag of ${{ inputs.tag }} for ${{ github.sha }}"
      shell: bash
    - run: entrypoint.sh "${{ inputs.tag }}"
      shell: bash
