name: 'Git Autotag'
description: 'Tag the repository when the action runs'
inputs:
  tag:
    description: The tag to create
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        echo "Fetching existing git tags"
        git fetch --quiet --prune --unshallow --tags
        echo $(git describe --dirty --tags)
      shell: bash
    - run: echo "Attempting to create a lightweight tag of ${{ inputs.tag }} for ${{ github.sha }}"
      shell: bash
    - run: bash $GITHUB_ACTION_PATH/entrypoint.sh "${{ inputs.tag }}"
      shell: bash
