name: 'Git Autotag'
description: 'Tag the repository when the action runs'
inputs:
  tag:
    description: The tag to create
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version-command }}
