name: 'Git Autotag'
description: 'Tag the repository when the action runs'
inputs:
  tag:
    description: The tag to create
    required: true
runs:
  using: "composite"
  steps:
    - name: "Fetching existing git tags"
      run: |
        git fetch --quiet --prune --unshallow --tags
        echo $(git describe --dirty --tags)
      shell: bash
    - name: "Creating lightweight tag ${{ inputs.tag }} for commit ${{ github.sha }}"
      run: $GITHUB_ACTION_PATH/entrypoint.sh "${{ inputs.tag }}"
      shell: bash
