name: A workflow for my Hello World file
on: push
  # branches:    # Array of patterns that match refs/heads
  #   - master 
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-18.04    
    steps:
    - uses: actions/checkout@master
    - name: Does this work?
      run: echo "$(git describe --dirty --tags)"
    - name: what about this
      run: echo $(cat mix.exs \
        | grep --line-buffer "version: " \
        | grep --extended-regexp --only-matching "[0-9\.]+")
        # APP_FULL_VERSION: ${{ git describe --dirty --tags)
      # env:
        # APP_VERSION: ${{ cat mix.exs | grep --line-buffer "version: " | grep --extended-regexp --only-matching "[0-9\.]+" }}
        # APP_FULL_VERSION: ${{ git describe --dirty --tags }}
    # - uses: ./action-a
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     MY_NAME: "Mona"
