name: A workflow for my Hello World file
on: 
  push:
    branches:
      - master 
jobs:
  build:
    name: Tag master using mix.exs
    runs-on: ubuntu-18.04    
    steps:
    - name: Checkout master
      uses: actions/checkout@master
    - name: The current tag
      run: echo $(git describe --dirty --tags)
    - name: Tag master depending on the value in mix.exs
      uses: ./action-a
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
