name: Creates a tag for the repo
on:
  push:
    branches:
      - master 
jobs:
  build:
    name: Tag repo using VERSION file
    runs-on: ubuntu-20.04    
    steps:
    - name: Checkout master
      uses: actions/checkout@v3
    - name: The new tag
      id: computed-tag
      run: |
        set -e
        TAG=$(cat VERSION)
        echo "tag=v$TAG" >> "$GITHUB_OUTPUT"
    - name: Tagging repo based on the contents of the VERSION file
      uses: djordon/git-autotag-action@master
      with:
        tag: ${{ steps.computed-tag.outputs.tag }}
